# db config

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.alibaba.druid.proxy.DruidDriver
    url: jdbc:mysql://127.0.0.1:3306/sily?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456



# mybatis
mybatis.type-aliases-package=com.my.blog.website.dao
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.gk.entity